### ISSUE TITLE
Problem with executions <Element 'executions' at 0x1527710> <type 'exceptions.UnboundLocalError'>

### ISSUE THREAD

**Issue by mathieuchateau** [phwitservices/RundeckLogfileCleanup#5]
Hello,

while working for most projects, I have this error for some of them:

`Problem with executions <Element 'executions' at 0x1527710> <type 'exceptions.UnboundLocalError'>
`
Do you know why ?

Rundek 2.6.9
Latest version of this script 

Thanks

**Comment by phwitservices** [comment]
I've had a quick look at the code and it looks like that exception is thrown in the main loop while gathering deletable jobs. I'll need to add a few more try/except clauses and some slightly more useful error messages. Somehow something isn't being declared properly, but I can't immediately see how.

Does this happen every time for you? Does it always happen for the same projects, or is it random?

**Comment by phwitservices** [comment]
... one more thing that might help, the log typically looks like this

PROJECT_NAME
    1: JOB_NAME
        Page 0 got X jobs
        Delete N jobs from this page
        Page 1 got X jobs
        Delete N jobs from this page

at what point does the error happen? i.e. between the project name & the job, while gathering jobs? Or at the end of gathering jobs as the delete happens.

**Comment by mathieuchateau** [comment]
Hello,
thanks for helping :)
It put it directly after job name. Others in same project do work.

Can it happens if too many execution ? Jobs where it fails are mainly executed every 5 mn for 1 year I think

```
  Unit - Files - Purge old core version
Problem with executions <Element 'executions' at 0xf73e10> <type 'exceptions.UnboundLocalError'>
    Unit - MariaDB - Out of band SQL queries
Problem with executions <Element 'executions' at 0xf73e10> <type 'exceptions.UnboundLocalError'>
```

**Comment by mathieuchateau** [comment]
Looks like it was a timeout issue.
After raising TIMEOUT to 300 in properties, it does work.
I tried before to reduce page to 100, but it was not enough.
Now put timeout to 300 and page to 1000, very slow but working.
I am still on H2, looking to purge first, then be able to get an export quick enough to migrate to MariaDB

**Comment by mathieuchateau** [comment]
still doing some tests, have new error messages for somes:

```
    Unit - MariaDB - Out of band SQL queries
Problem with execution listing <Response [200]>
Problem with executions None <type 'exceptions.AttributeError'>
```

**Comment by phwitservices** [comment]
I can't help you with the MariaDB error I'm afraid, I run through SQLServer. Perhaps there is a timeout on the DB connection?
I've got a version here that allows you to set a maximum number of deleted jobs and better error messages. I'm just trying to check it into this site.

**Comment by phwitservices** [comment]
I've pushed the changes. At the very least the main loop exception should show a stack trace so we can see where we have the problem. Try moving the new MAX_DELETE parameter down to a few hundred, my terrible old Windows 2003 servers choke if I try and delete more than about 1000 executions at a time. The downside is that the executions always come in reverse time order, so the oldest tasks are the last to be deleted.
You could also try setting the MAX_DAYS higher to try and delete the oldest executions first. Then progressively lower the value & rerun. I'm running the delete nightly to try and reduce the workload.
If the API let us return the jobs sorted so that we got the oldest first it would be very useful.

**Comment by phwitservices** [comment]
I've just seen this

```
Problem with execution listing <Response [500]>
Traceback (most recent call last):
  File "Z:\Documents\Aptana Studio 3 Workspace\RundeckLogfileCleanupGIT\RundeckLogfileCleanup.py", line 143, in <module>
    print "        Page {0} got {1} jobs".format(page,execution_root.attrib['count'])
AttributeError: 'NoneType' object has no attribute 'attrib'

Problem with executions None <type 'exceptions.AttributeError'>

```

The 500 error is a server-side error (unexpected situation). If this is what you are seeing, and it is the same every time you run the script, then it looks like there is a problem with your server. This generally seems to fit in with your earlier comment that you were getting [200]'s and an error report from your DB.  Most likely, I suppose, is that there is a resource issue that is halting the job query causing Rundeck to return the 500 error. Try reducing all the resource parameters ("PAGE_SIZE" etc...) and increasing the timeouts.

**Comment by mathieuchateau** [comment]
Hello,

since I increased the timeout, it's working for all jobs on the 3 rundeck we have :)

It's currently not mySQL, but the default H2 Database, which is quite slow
thanks for your help

**Comment by phwitservices** [comment]
Good to hear that you've found a way around the problem. I'm going to close this issue.
